# Generated by Django 3.2.3 on 2021-05-28 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='description',
            field=models.CharField(blank=True, help_text='Краткое описание профессии', max_length=1000, null=True, verbose_name='Описание профессии'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор данного профиля', primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор данного пользователя', primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
