# Generated by Django 3.2.3 on 2021-05-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profession_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='image_url',
            field=models.CharField(blank=True, help_text='Фото профиля (необязательно)', max_length=1000, null=True, verbose_name='Фото профиля'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='insta_profile',
            field=models.CharField(blank=True, help_text='Имя профиля в инстаграм', max_length=500, null=True, verbose_name='Профиль в инстаграм'),
        ),
    ]
