# Generated by Django 3.2.3 on 2021-05-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210529_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professioninstance',
            options={},
        ),
        migrations.AddField(
            model_name='siteuser',
            name='insta_verified',
            field=models.BooleanField(default=False, verbose_name='Профиль инстаграм подтверждён'),
        ),
    ]
